# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
deployment:
  strategy:
    maxUnavailable: 50%
    maxSurge: 50%
image:
  tag: stable
  pullPolicy: Always
  secrets:
    - name: gitlab-registry
application:
  track: stable
  tier: web
service:
  externalPort: 5000
  internalPort: 5000
resources:

