# Site settings available under site.*
title: Triple D
header-img: img/home-bg.jpg
email: blog@tripled.io
copyright_name: Triple D
description: "TripleD blog"
disqus: "TripleD"
google_tracking_id: "UA-115161766-1"
permalink: /:day/:month/:year/:title/
url: //www.tripled.io
twitter_username: tripled_io
email_username: info@tripled.io

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num/"
plugins: [jekyll-paginate,jekyll-feed]

# authors
authors:
  domenique:
    username: "domenique"
    name: "Domenique Tilleuil"
    bio: "Software craftsman journeyman. Professional java code juggler. Avid fan of DDD and XP practices"
    location: "Zoersel, Belgium"
    image: "/img/authors/domenique.png"
  guido:
      username: "guido"
      name: "Guido Dechamps"
      bio: "Old cranky 'veteran' software engineer. All opinions are my own."
      location: "Belgium"
      image: "/img/authors/guido.jpg"
      web: https://twitter.com/dechampsgu
  kris:
      username: "kris"
      name: "Kris Hofmans"
      bio: "Finds Software Development interesting, especially the ways people find to mess it up. Gets things deployed."
      location: "Belgium"
      image: "/img/authors/kris.jpg"
