# Site settings available under site.*
title: Triple D
header-img: img/home-bg.jpg
email: blog@tripled.io
copyright_name: Triple D
description: "TripleD blog"
disqus: "TripleD"
google_tracking_id: "UA-115161766-1"
permalink: /:day/:month/:year/:title/
url: //www.tripled.io
twitter_username: tripled_io
email_username: info@tripled.io

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num/"
plugins: [jekyll-paginate,jekyll-feed]

