# Site settings available under site.*
title: Triple D
header-img: img/home-bg.jpg
email: blog@tripled.io
copyright_name: Triple D
description: "TripleD blog"
disqus: "TripleD"
google_tracking_id: "UA-86097038-1"
permalink: /:day/:month/:year/:title/
url: //www.tripled.io
twitter_username: tripled_io
email_username: info@tripled.io

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num/"
plugins: [jekyll-paginate,jekyll-feed]

# authors
authors:
  domenique:
    username: "domenique"
    name: "Domenique Tilleuil"
    bio: "Software craftsmen journeyman. Professional java code juggler. Avid fan of DDD and XP practices"
    location: "Zoersel, Belgium"
    image: "/img/domenique.png"
  guido:
      username: "guido"
      name: "Guido Dechamps"
      bio: "Old cranky software craftsman"
      location: "Lokeren, Belgium"
      image: "/img/guido.jpg"
