# Site settings available under site.*
encoding: utf-8
title: Triple D
copyright_name: Triple D
description: "Triple D is a belgian based software company."
disqus: "TripleD"
google_tracking_id: "UA-115161766-1"
permalink: /:day/:month/:year/:title/
url: https://www.tripled.io
email: info@tripled.io
logo: https://www.tripled.io/img/logo-alt.png
twitter:
    username: tripled_io
    card: summary
linkedin:
    username: triple-d-io
collections:
    events:
        output: true
        permalink: /:collection/:title
# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "/blog/page:num/"
plugins: [jekyll-paginate,jekyll-feed,jekyll-seo-tag,jekyll-sitemap]